openapi: 3.0.1

info:
  title: Orders API
  description: API for managing orders
  version: 1.0.0

servers:
  - url: http://localhost:9000/api/v1
    description: Local development server

tags:
  - name: Orders
    description: Operations related to orders

paths:
  /orders/all:
    get:
      tags:
        - Orders
      summary: Get all orders
      description: Retrieve a list of all orders

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseHeader:
                    type: object
                  ResponseBody:
                    type: array
                    items:
                      $ref: '#/components/schemas/OrderResponse'
              example:
                {
                  "ResponseHeader": {
                    "StatusCode": 1000,
                    "StatusMessage": "Success",
                    "StatusDesc": "OK",
                    "RequestId": "REQ9001"
                  },
                  "ResponseBody": [
                    {
                      "id": 1,
                      "user_id": 1,
                      "product": "Laptop",
                      "amount": 1500.50,
                      "created_at": "2025-12-08T10:00:00Z"
                    },
                    {
                      "id": 2,
                      "user_id": 2,
                      "product": "Mobile",
                      "amount": 800.00,
                      "created_at": "2025-12-08T11:15:00Z"
                    }
                  ]
                }

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
              examples:
                ServerError:
                  summary: Internal server error
                  value:
                    {
                      "ResponseHeader": {
                        "StatusCode": 1001,
                        "StatusMessage": "Error",
                        "StatusDesc": "Internal system error",
                        "RequestId": "REQ5009",
                        "ErrorCode": "ERR_10000000",
                        "ErrorMessage": "Unexpected system failure"
                      },
                      "ResponseBody": { }
                    }

      security:
        - default:
            - common

      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false


  /orders/create:
    post:
      tags:
        - Orders
      summary: Create a new order
      description: Create a new order (calls `create_order` in backend)

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreate'
            example:
              {
                "user_id": 1,
                "product": "Laptop",
                "amount": 1500.50
              }

      responses:
        '200':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseHeader:
                    type: object
                  ResponseBody:
                    $ref: '#/components/schemas/OrderResponse'
              example:
                {
                  "ResponseHeader": {
                    "StatusCode": 1000,
                    "StatusMessage": "Success",
                    "StatusDesc": "Order created successfully",
                    "RequestId": "REQ9010"
                  },
                  "ResponseBody": {
                    "id": 1,
                    "user_id": 1,
                    "product": "Laptop",
                    "amount": 1500.50,
                    "created_at": "2025-12-08T10:00:00Z"
                  }
                }

        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
              examples:
                ValidationError:
                  summary: Validation error
                  value:
                    {
                      "ResponseHeader": {
                        "StatusCode": 1001,
                        "StatusMessage": "Error",
                        "StatusDesc": "Validation failed",
                        "RequestId": "REQ4010",
                        "ErrorCode": "ERR_1000005",
                        "ErrorMessage": "user_id, product and amount are required"
                      },
                      "ResponseBody": { }
                    }

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
              examples:
                ServerError:
                  summary: Internal server error
                  value:
                    {
                      "ResponseHeader": {
                        "StatusCode": 1001,
                        "StatusMessage": "Error",
                        "StatusDesc": "Internal system error",
                        "RequestId": "REQ5010",
                        "ErrorCode": "ERR_10000000",
                        "ErrorMessage": "Unexpected error occurred"
                      },
                      "ResponseBody": { }
                    }

      security:
        - default:
            - common

      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false


components:
  schemas:
    OrderCreate:
      type: object
      required:
        - user_id
        - product
        - amount
      properties:
        user_id:
          type: integer
          example: 1
        product:
          type: string
          example: "Laptop"
        amount:
          type: number
          format: float
          example: 1500.50

    OrderResponse:
      allOf:
        - $ref: '#/components/schemas/OrderCreate'
        - type: object
          properties:
            id:
              type: integer
              example: 1
            created_at:
              type: string
              format: date-time
              example: "2025-12-08T10:00:00Z"

  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes:
            common: common access


x-wso2-api-key-header: ApiKey
x-wso2-auth-header: Authorization

x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
    - apikey
    - Internal-Key
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS

x-wso2-production-endpoints:
  urls:
    - 'http://localhost:9000/api/v1'
  type: http

x-wso2-sandbox-endpoints:
  urls:
    - 'http://localhost:9000/api/v1'
  type: http

x-wso2-basePath: /healthcheckapi/1.0.0

x-wso2-transports:
  - http
  - https

x-wso2-application-security:
  security-types:
    - oauth2
  optional: false

x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
