openapi: 3.0.3
info:
  title: Orders API
  description: API for managing orders
  version: 1.0.0.

servers:
  - url: http://localhost:9000/api/v1
    description: Local development server

tags:
  - name: Orders
    description: Operations related to orders

paths:
  /orders/all:
    get:
      tags:
        - Orders
      summary: Get all orders
      description: Retrieve a list of all orders
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false

  /orders/create:
    post:
      tags:
        - Orders
      summary: Create a new order
      description: Create a new order (calls `create_order` in backend)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreate'
            example:
              user_id: 1
              product: "Laptop"
              amount: 1500.50
      responses:
        '200':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid input
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false

components:
  schemas:
    OrderCreate:
      type: object
      required:
        - user_id
        - product
        - amount
      properties:
        user_id:
          type: integer
          example: 1
        product:
          type: string
          example: "Laptop"
        amount:
          type: number
          format: float
          example: 1500.50

    OrderResponse:
      allOf:
        - $ref: '#/components/schemas/OrderCreate'
        - type: object
          properties:
            id:
              type: integer
              example: 1
            created_at:
              type: string
              format: date-time
              example: "2025-12-08T10:00:00Z"

  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}
